language: python
python: 
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"

install: 
  - pip install coverage
  - pip install python-coveralls

script: coverage run --source=gallows.py setup.py test

after_success: 
  - coveralls

deploy: 
  provider: pypi
  user: vijaykumar
  password: 
    secure: gSJMMPUd5+Trg4vhcKrbAjcryzreH5ie/vPuym8iuqVYn9jBUeOxBmZSvLH9aIskvG4Bf9gzu4dw7sLB1updh/RazcsVGzR0aO0kwZP5Y2IQTtnHH6R51ESIi6yW9N+T8hbYca34UOPPvo2xduN4vG1PCPmI2W4AQ/hhWAP95vE=
  on: 
    tags: true
